apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-tracker.fullname" . }}-config
  namespace: {{ include "job-tracker.namespace" . }}
  labels:
    {{- include "job-tracker.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.app.name | quote }}
  APP_ENV: {{ .Values.app.env | quote }}
  LOGO_DIR: {{ .Values.app.logoDir | quote }}
  SEED_LOGO_DIR: "logos"
  {{ if .Values.linkedinLookup.enabled }}
  LINKEDIN_LOOKUP_URL: {{ printf "http://%s-linkedin-lookup:%v" (include "job-tracker.fullname" .) .Values.linkedinLookup.service.port | quote }}
  {{ else }}
  LINKEDIN_LOOKUP_URL: ""
  {{ end }}
